
language: c
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild /p:Configuration=Release NCommander.sln 
  - nunit-console ./NCommanderTests/bin/Debug/NCommanderTests.dll

branches:
  only:
    - master
